Update readme to reflect changes made in #34
qnighy/yasna.rs pull request #35
Opened 2019-02-25 23:27 UTC by jack-fortanix

I just noticed this in the readme. With #34 merged IA5 and BMP strings are now supported.

2019-02-25 23:44 UTC, est31 requested changes
Could you edit the deserialization section as well? Otherwise fine.

2019-02-26 15:57 UTC, jack-fortanix commented
Updated

2019-02-26 16:58 UTC, est31 approved these changes

2019-02-26 16:58 UTC, merged

2019-02-26 16:58 UTC, est31 commented
Thanks for the PR!